# Generated by Django 5.1.1 on 2024-09-18 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.TextField(blank=True, null=True),
        ),
    ]
