# Generated by Django 5.1.1 on 2024-10-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_project_is_completed_subtask_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='color',
            field=models.CharField(default='#9b9b9b', max_length=7),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(default='#9b9b9b', max_length=7),
        ),
    ]
