# Generated by Django 5.1.1 on 2024-10-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_project_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
