# Generated by Django 5.1.1 on 2024-11-12 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color',
        ),
        migrations.RemoveField(
            model_name='task',
            name='color',
        ),
        migrations.DeleteModel(
            name='SubTask',
        ),
    ]
