# Generated by Django 5.1.1 on 2024-11-13 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0011_project_due_date_task_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todolist.project')),
            ],
        ),
    ]
