# Generated by Django 5.1.1 on 2025-01-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0016_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='noti_type',
            new_name='notification_type',
        ),
    ]
