# Generated by Django 5.1.1 on 2025-01-11 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0018_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationtype',
            name='type_name',
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='identifier',
            field=models.CharField(default='default=unkown', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(default='start', max_length=100),
            preserve_default=False,
        ),
    ]
